spring:
  datasource:
    url: jdbc:h2:file:~/db/bank_api
    #    url: jdbc:postgresql:/localhost:5432/bank_api
    username: tiago
    password: 123123
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update